/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import dfl.all;

import std.string;


class EnterVert: dfl.form.Form
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.label.Label label1;
	dfl.button.Button button1;
	dfl.button.Button button2;
	dfl.textbox.TextBox textBox2;
	//~Entice Designer variables end here.
	
	
	this(char[][] lines = [])
	{
		initializeEnterVert(lines);
		
		//@  Other enterVert initialization code here.
		
	}
	
	
	private void initializeEnterVert(char[][] lines = [])
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Form
		text = "enter Vert";
		clientSize = dfl.all.Size(496, 236);
		//~DFL dfl.label.Label=label1
		label1 = new dfl.label.Label();
		label1.name = "label1";
		label1.text = "n {liczba elementow}"~newline~"{elementy pokrywane przez 0}"~newline~"{elementy pokrywajace 0}"~newline~"{elementy pokrywane przez 1}"~
					newline~"."~newline~"."~newline~"."~newline~"{elementy pokrywane przez n-1}"~newline~"{elementy pokrywajace n-1}"~newline~newline~newline~"Elementy w listach oddzielane spacjami.";
		label1.bounds = dfl.all.Rect(256, 8, 240, 184);
		label1.parent = this;
		//~DFL dfl.button.Button=button1
		button1 = new dfl.button.Button();
		button1.name = "button1";
		button1.text = "OK";
		button1.bounds = dfl.all.Rect(248, 200, 112, 32);
		button1.click ~= &button1_click;
		button1.parent = this;
		//~DFL dfl.button.Button=button2
		button2 = new dfl.button.Button();
		button2.name = "button2";
		button2.text = "Anuluj";
		button2.bounds = dfl.all.Rect(376, 200, 112, 32);
		button2.click ~= &button2_click;
		button2.parent = this;
		//~DFL dfl.textbox.TextBox=textBox2
		textBox2 = new dfl.textbox.TextBox();
		textBox2.name = "textBox2";
		textBox2.font = new dfl.all.Font("Courier New", 10f, dfl.all.FontStyle.REGULAR);
		textBox2.multiline = true;
		textBox2.scrollBars = dfl.all.ScrollBars.BOTH;
		textBox2.bounds = dfl.all.Rect(0, 8, 248, 184);
		if (lines !is null && lines.length > 0) {
			textBox2.lines = lines;
		}
		textBox2.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
	
	private void button1_click(Object sender, EventArgs ea) {
		this.dialogResult = DialogResult.OK;
		this.visible(false);
		//this.dispose();
	}
	
	
	private void button2_click(Object sender, EventArgs ea) {
		this.dialogResult = DialogResult.CANCEL;
		this.visible(false);
		//this.dispose();
	}
}

