/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/
module randomarcposet;

private {
	import dfl.all;
	
	import std.stdio;
	import std.conv;
}




class RandomArcPoset: dfl.form.Form
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.label.Label label3;
	dfl.button.Button okButton;
	dfl.button.Button canButton;
	dfl.textbox.TextBox posetArcNumBox;
	dfl.textbox.TextBox dummyArcNumBox;
	dfl.label.Label label4;
	//~Entice Designer variables end here.
	
	bool posetFilled, dummyFilled;
	
	this()
	{
		initializeRandomPoset();
		
		//@  Other randomPoset initialization code here.
		posetArcNumBox.textChanged ~= &posetArcNumBox_textChanged;
		posetArcNumBox.visibleChanged ~= &posetArcNumBox_visibleChanged;
		dummyArcNumBox.textChanged ~= &dummyArcNumBox_textChanged;
		okButton.click ~= &okButton_click;
		canButton.click ~= &canButton_click;
		this.acceptButton(okButton);
		this.cancelButton(canButton);
	}
	
	
	private void posetArcNumBox_textChanged(Object sender, EventArgs ea) {
		char[] content;
		bool good = true;
		if (posetArcNumBox.lines.length == 0) {
			posetFilled = false;
			okButton.enabled(false);
			return;
		}
		for (uint i = 0; i < posetArcNumBox.lines[0].length; i++) {
			if ((posetArcNumBox.lines[0][i] >= '0') && (posetArcNumBox.lines[0][i] <= '9')) {
				char[] got = posetArcNumBox.lines[0].dup;
				if (got.length > 9) {
					good = false;
					break;
				}
				content ~= posetArcNumBox.lines[0][i];
			} else {
				good = false;
			}
		}
		if (good) {
			if ((posetArcNumBox.lines.length > 0) && (posetArcNumBox.lines[0].length > 0)) {
				//okButton.enabled(true);
				posetFilled = true;
			} else {
				//okButton.enabled(false);
				posetFilled = false;
			}
		} else {
			//writefln(content);
			/+posetArcNumBox.clear;
		
			posetArcNumBox.lines[0] = content;
			posetArcNumBox.refresh();
			posetArcNumBox.redraw();+/
			posetArcNumBox.text = content;
			if (content.length > 0) {
				//okButton.enabled(true);
				posetFilled = true;
			} else {
				//okButton.enabled(false);
				posetFilled = false;
			}
		}
		if ((posetFilled) && (dummyFilled)) {
			okButton.enabled(true);
		} else {
			okButton.enabled(false);
		}
	}
	
	
	private void dummyArcNumBox_textChanged(Object sender, EventArgs ea) {
		char[] content;
		bool good = true;
		if (dummyArcNumBox.lines.length == 0) {
			dummyFilled = false;
			okButton.enabled(false);
			return;
		}
		for (uint i = 0; i < dummyArcNumBox.lines[0].length; i++) {
			if ((dummyArcNumBox.lines[0][i] >= '0') && (dummyArcNumBox.lines[0][i] <= '9')) {
				char[] got = dummyArcNumBox.lines[0].dup;
				if (got.length > 9) {
					good = false;
					break;
				}
				content ~= dummyArcNumBox.lines[0][i];
			} else {
				good = false;
			}
		}
		if (good) {
			if ((dummyArcNumBox.lines.length > 0) && (dummyArcNumBox.lines[0].length > 0)) {
				//okButton.enabled(true);
				dummyFilled = true;
			} else {
				//okButton.enabled(false);
				dummyFilled = false;
			}
		} else {
			//writefln(content);
			/+dummyArcNumBox.clear;
		
			dummyArcNumBox.lines[0] = content;
			dummyArcNumBox.refresh();
			dummyArcNumBox.redraw();+/
			dummyArcNumBox.text = content;
			if (content.length > 0) {
				//okButton.enabled(true);
				dummyFilled = true;
			} else {
				//okButton.enabled(false);
				dummyFilled = false;
			}
		}
		if ((posetFilled) && (dummyFilled)) {
			okButton.enabled(true);
		} else {
			okButton.enabled(false);
		}
	}
	
	
	private void okButton_click(Object sender, EventArgs ea) {
		this.dialogResult = DialogResult.OK;
		this.visible(false);
		//this.dispose();
	}
	
	
	private void canButton_click(Object sender, EventArgs ea) {
		this.dialogResult = DialogResult.CANCEL;
		this.visible(false);
		//this.dispose();
	}
	
	
	private void posetArcNumBox_visibleChanged(Object sender, EventArgs ea) {
		if (posetArcNumBox.visible == true) posetArcNumBox.focus();
	}
	
	
	private void initializeRandomPoset()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Form
		text = "Losuj poset łukowo";
		clientSize = dfl.all.Size(264, 140);
		//~DFL dfl.label.Label=label3
		label3 = new dfl.label.Label();
		label3.name = "label3";
		label3.text = "Liczba łuków posetu";
		label3.bounds = dfl.all.Rect(16, 16, 120, 16);
		label3.parent = this;
		//~DFL dfl.button.Button=okButton
		okButton = new dfl.button.Button();
		okButton.name = "okButton";
		okButton.enabled = false;
		okButton.text = "OK";
		okButton.bounds = dfl.all.Rect(16, 112, 96, 24);
		okButton.parent = this;
		//~DFL dfl.button.Button=canButton
		canButton = new dfl.button.Button();
		canButton.name = "canButton";
		canButton.text = "Anuluj";
		canButton.bounds = dfl.all.Rect(152, 112, 96, 24);
		canButton.parent = this;
		//~DFL dfl.textbox.TextBox=posetArcNumBox
		posetArcNumBox = new dfl.textbox.TextBox();
		posetArcNumBox.name = "posetArcNumBox";
		posetArcNumBox.backColor = dfl.all.Color(255, 255, 255);
		posetArcNumBox.borderStyle = dfl.all.BorderStyle.FIXED_SINGLE;
		posetArcNumBox.bounds = dfl.all.Rect(16, 32, 232, 24);
		posetArcNumBox.parent = this;
		//~DFL dfl.textbox.TextBox=dummyArcNumBox
		dummyArcNumBox = new dfl.textbox.TextBox();
		dummyArcNumBox.name = "dummyArcNumBox";
		dummyArcNumBox.backColor = dfl.all.Color(255, 255, 255);
		dummyArcNumBox.borderStyle = dfl.all.BorderStyle.FIXED_SINGLE;
		dummyArcNumBox.bounds = dfl.all.Rect(16, 80, 232, 24);
		dummyArcNumBox.parent = this;
		//~DFL dfl.label.Label=label4
		label4 = new dfl.label.Label();
		label4.name = "label4";
		label4.text = "Liczba łuków pozornych";
		label4.bounds = dfl.all.Rect(16, 64, 120, 16);
		label4.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

