/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import dfl.all;


class ReportWindow: dfl.form.Form
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.textbox.TextBox textBox3;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeReportWindow();
		
		//@  Other ReportWindow initialization code here.
		
	}
	
	
	private void initializeReportWindow()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Form
		text = "Report Window";
		clientSize = dfl.all.Size(284, 84);
		//~DFL dfl.textbox.TextBox=textBox3
		textBox3 = new dfl.textbox.TextBox();
		textBox3.name = "textBox3";
		textBox3.dock = dfl.all.DockStyle.FILL;
		textBox3.multiline = true;
		textBox3.readOnly = true;
		textBox3.scrollBars = dfl.all.ScrollBars.VERTICAL;
		textBox3.bounds = dfl.all.Rect(0, 0, 284, 84);
		textBox3.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

